name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"
permissions:
  contents: write # required to create a release
  id-token: write # required for cosign
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        with:
          aqua_version: v1.38.0
      - run: |
          cosign sign-blob \
            --output-certificate=aqua-installer.pem \
            --output-signature aqua-installer.sig \
            --oidc-provider github \
            aqua-installer
        env:
          COSIGN_EXPERIMENTAL: "1"
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            aqua-installer.sig
            aqua-installer.pem
          draft: true
