name: test
on: pull_request
permissions:
  contents: read # required for checkout
  id-token: write # required for cosign
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: aquaproj/aqua-installer@c553e04154f1f3b7e5eb35da058db3bb782bee8a # tag=v1.1.2
        with:
          aqua_version: v1.25.0
      - run: |
          cosign sign-blob \
            --output-certificate=aqua-installer.pem \
            --output-signature aqua-installer.sig \
            --oidc-provider github \
            aqua-installer
        env:
          COSIGN_EXPERIMENTAL: "1"
