name: test
on: pull_request
permissions:
  contents: read # required for checkout
  id-token: write # required for cosign
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
        with:
          aqua_version: v1.38.0
      - run: |
          cosign sign-blob \
            --output-certificate=aqua-installer.pem \
            --output-signature aqua-installer.sig \
            --oidc-provider github \
            aqua-installer
        env:
          COSIGN_EXPERIMENTAL: "1"
